### ISSUE TITLE
`generate_cask` task failing since June 17th, 19:05 GMT-4

### ISSUE THREAD

**Issue by stephenmcgruer** [foolip/safari-technology-preview-updater#101]
See https://dev.azure.com/foolip/safari-technology-preview-updater/_build?definitionId=12&_a=summary

Example failure: https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=3275&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=5852bf5a-5a02-52f3-bee8-4fdc90cda9d0

```
Starting: generate cask
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
node gen-cask.js
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/work/_temp/4c8b6d0e-8f2f-43ba-ac50-b05ef4a21712.sh
Error: Expecting Catalina + Big Sur packages but got {"monterey":{"url":"https://secure-appldnld.apple.com/STP/001-66930-20210616-c91fc8a5-bfeb-47ec-80c2-0d54c6ebbcee/SafariTechnologyPreview.dmg","sha256":"d7547c77c709db6f551a5be1c60fcdff3b116579aa24038ebe2936003e8c3af4"},"big_sur":{"url":"https://secure-appldnld.apple.com/STP/071-49115-20210616-CFF65F23-A558-4BE9-BC39-636914359EBC/SafariTechnologyPreview.dmg","sha256":"6896b6db3f25937a85dc6827b0e65f8e04f868fc2a8d38bbc7c86f342bb4363b"}}
    at generateCask (/Users/runner/work/1/s/gen-cask.js:64:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
##[error]Bash exited with code '1'.
Finishing: generate cask
```

**Comment by stephenmcgruer** [comment]
Looks like https://github.com/foolip/safari-technology-preview-updater/blob/main/gen-cask.js#L61 will need to be updated to now expect Monterey and Big Sur, rather than Catalina and Big Sur. 

One interesting question is whether WPT runs its Azure Pipelines jobs on Big Sur or not (I cannot recall); if STP is now only available for Big Sur onwards that may be a problem? (I'm just speculating here, haven't thought about it much).

cc @gsnedders as an FYI

**Comment by stephenmcgruer** [comment]
https://github.com/actions/virtual-environments/issues/2072#issuecomment-823881568 might be the issue for Big Sur support in Azure Pipelines in general (not just for WPT), and it seems like the answer is not good (working on it but no ETA...).

**Comment by foolip** [comment]
@gsnedders did you ask our friends at Microsoft about Big Sur support on Azure Pipelines?

**Comment by foolip** [comment]
Last time I fixed this with https://github.com/foolip/safari-technology-preview-updater/commit/92c4f8d51c646661da7f5e128fe113d63bd535e0, but now there's an extra challenge.

https://developer.apple.com/safari/download/ only has STP for macOS 12 beta, which of course is much further away still from being available in a CI system. But anyway, scraping code updated in https://github.com/foolip/safari-technology-preview-updater/pull/102 so that we'll get a usable cask when Big Sur is added.

**Comment by gsnedders** [comment]
> @gsnedders did you ask our friends at Microsoft about Big Sur support on Azure Pipelines?

I didn't on the basis of what @stephenmcgruer linked to above, where it's very much clear that they're hoping to at some point but have no clear timeline to communicate.

> https://developer.apple.com/safari/download/ only has STP for macOS 12 beta, which of course is much further away still from being available in a CI system. But anyway, scraping code updated in #102 so that we'll get a usable cask when Big Sur is added.

Yeah, STP 126 for Big Sur got pulled. :(

**Comment by foolip** [comment]
Reopening since the problem isn't solved in practice yet, even if the code was updated.

**Comment by foolip** [comment]
This hasn't happened again and I'm going to archive this repo.
