### ISSUE TITLE
STP 100 update broke scraping script

### ISSUE THREAD

**Issue by foolip** [foolip/safari-technology-preview-updater#52]
https://developer.apple.com/safari/download/ says 💯 instead of 100, and this broke the version detection in https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=1383&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=5852bf5a-5a02-52f3-bee8-4fdc90cda9d0&l=22.

Oops :)

@apple-web-evangelist FYI

**Comment by Hexcles** [comment]
Looks like this has been fixed by dce0e0d03a2d172c98a1e2b62b72fca141a641d4

**Comment by foolip** [comment]
Yeah, forgot to link it :)
