### ISSUE TITLE
Need extra scopes on token

### ISSUE THREAD

**Issue by gsnedders** [foolip/safari-technology-preview-updater#97]
```
 ! [remote rejected]       safari-technology-preview-125 -> safari-technology-preview-125 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/interfaces.yml` without `workflow` scope)
```

**Comment by foolip** [comment]
Hmm, I didn't realize this is possible to fix by adding a scope to the token, I've just been updating the main branch of the fork instead to work around the problem. I'll try updating the token now.

Also, it would be great to move this into WPT as some Python code that does the same thing. It's just scraping a site and filling in a template in the end.

**Comment by foolip** [comment]
Awesome, that fixed the problem: https://github.com/web-platform-tests/wpt/pull/29133
